//! launchd LaunchAgent generation + (un)install.
//!
//! Follows the macOS-external-volume rules: the binary is copied to the boot
//! drive (`~/bin`), the agent invokes `/bin/sh <launcher>` (never the binary
//! directly, to dodge the launcher's provenance xattr / Gatekeeper), logs go to
//! `~/Library/Logs`, and no `WorkingDirectory` points at `/Volumes`.

use std::path::{Path, PathBuf};

pub const LABEL: &str = "show.laowang.macleaner";

pub fn bin_path(home: &Path) -> PathBuf {
    home.join("bin/macleaner")
}
pub fn launcher_path(home: &Path) -> PathBuf {
    home.join("bin/macleaner-launcher.sh")
}
pub fn plist_path(home: &Path) -> PathBuf {
    home.join(format!("Library/LaunchAgents/{LABEL}.plist"))
}
pub fn log_file(home: &Path) -> PathBuf {
    home.join("Library/Logs/macleaner/macleaner.log")
}

/// The launcher script. Sets a rich PATH (launchd's is minimal) and execs the
/// boot-drive binary with `run`.
pub fn launcher_script() -> String {
    "#!/bin/sh\n\
     # macleaner launchd launcher (generated by `macleaner install`).\n\
     # The binary lives on the boot drive: launchd/xpcproxy refuse ad-hoc-signed\n\
     # Mach-O binaries on /Volumes.\n\
     export PATH=\"/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin\"\n\
     exec \"$HOME/bin/macleaner\" run\n"
        .to_string()
}

/// Escape XML text content so a path containing `&`, `<`, or `>` cannot produce
/// a malformed plist (which launchd would silently fail to load). `&` must be
/// replaced first so the entities it introduces are not re-escaped.
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// The LaunchAgent plist. Runs at load (catch-up after reboot) and daily at
/// `hour:minute`; the binary's own once-per-day guard prevents over-running.
pub fn plist(launcher: &Path, log: &Path, hour: u32, minute: u32) -> String {
    let launcher = xml_escape(&launcher.display().to_string());
    let log = xml_escape(&log.display().to_string());
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>{launcher}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>{hour}</integer>
        <key>Minute</key>
        <integer>{minute}</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{log}</string>
    <key>StandardErrorPath</key>
    <string>{log}</string>
    <key>ProcessType</key>
    <string>Background</string>
    <key>LowPriorityIO</key>
    <true/>
    <key>Nice</key>
    <integer>5</integer>
</dict>
</plist>
"#,
        label = LABEL,
        launcher = launcher,
        log = log,
        hour = hour,
        minute = minute,
    )
}

/// Install the LaunchAgent: copy `source_binary` to `~/bin`, write the launcher
/// and plist, create the log dir, then (re)load via launchctl. Returns a log of
/// the steps performed.
pub fn install(
    home: &Path,
    source_binary: &Path,
    hour: u32,
    minute: u32,
) -> anyhow::Result<Vec<String>> {
    let mut steps = Vec::new();
    let bin = bin_path(home);
    let launcher = launcher_path(home);
    let plist_p = plist_path(home);
    let log = log_file(home);

    for dir in [
        bin.parent(),
        launcher.parent(),
        plist_p.parent(),
        log.parent(),
    ]
    .into_iter()
    .flatten()
    {
        std::fs::create_dir_all(dir)?;
    }

    std::fs::copy(source_binary, &bin)?;
    set_executable(&bin)?;
    steps.push(format!("copied binary → {}", bin.display()));

    std::fs::write(&launcher, launcher_script())?;
    set_executable(&launcher)?;
    steps.push(format!("wrote launcher → {}", launcher.display()));

    std::fs::write(&plist_p, plist(&launcher, &log, hour, minute))?;
    steps.push(format!("wrote plist → {}", plist_p.display()));

    let uid = unsafe { libc::getuid() };
    // Unload any prior instance (ignore failure), then bootstrap the new one.
    let _ = run_launchctl(&["bootout", &format!("gui/{uid}/{LABEL}")]);
    let out = run_launchctl(&[
        "bootstrap",
        &format!("gui/{uid}"),
        &plist_p.to_string_lossy(),
    ]);
    match out {
        Ok(true) => steps.push(format!("launchctl bootstrap gui/{uid} ✓")),
        Ok(false) | Err(_) => steps.push(
            "launchctl bootstrap reported an issue — check `launchctl print gui/$UID/show.laowang.macleaner`"
                .to_string(),
        ),
    }
    Ok(steps)
}

/// Uninstall: unload the agent and remove the plist + launcher (the binary in
/// `~/bin` is left in place so manual `macleaner` invocation still works).
pub fn uninstall(home: &Path) -> anyhow::Result<Vec<String>> {
    let mut steps = Vec::new();
    let uid = unsafe { libc::getuid() };
    let _ = run_launchctl(&["bootout", &format!("gui/{uid}/{LABEL}")]);
    steps.push(format!("launchctl bootout gui/{uid}/{LABEL}"));
    for p in [plist_path(home), launcher_path(home)] {
        if p.exists() {
            std::fs::remove_file(&p)?;
            steps.push(format!("removed {}", p.display()));
        }
    }
    Ok(steps)
}

fn set_executable(p: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(p)?.permissions();
    perm.set_mode(0o755);
    std::fs::set_permissions(p, perm)
}

fn run_launchctl(args: &[&str]) -> std::io::Result<bool> {
    Ok(std::process::Command::new("launchctl")
        .args(args)
        .output()?
        .status
        .success())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plist_meets_ac7() {
        let home = Path::new("/Users/cw");
        let launcher = launcher_path(home);
        let log = log_file(home);
        let xml = plist(&launcher, &log, 3, 0);

        // /bin/sh + launcher, not the binary directly
        assert!(xml.contains("<string>/bin/sh</string>"));
        assert!(xml.contains("macleaner-launcher.sh"));
        // log paths under ~/Library/Logs
        assert!(xml.contains("/Users/cw/Library/Logs/macleaner/macleaner.log"));
        // a daily schedule
        assert!(xml.contains("StartCalendarInterval"));
        assert!(xml.contains("<key>Hour</key>"));
        // never a /Volumes working directory
        assert!(!xml.contains("WorkingDirectory"));
        assert!(!xml.contains("/Volumes"));
    }

    #[test]
    fn plist_escapes_xml_special_chars() {
        // A $HOME containing XML metacharacters must not produce malformed XML
        // (red-team finding). Covers the full xml_escape contract: & < >.
        let launcher = Path::new("/Users/a&<b>/bin/macleaner-launcher.sh");
        let log = Path::new("/Users/a&<b>/Library/Logs/macleaner/macleaner.log");
        let xml = plist(launcher, log, 3, 0);
        assert!(xml.contains("/Users/a&amp;&lt;b&gt;/bin/macleaner-launcher.sh"));
        assert!(
            !xml.contains("a&<b>"),
            "no raw unescaped &, <, or > in the plist"
        );
    }

    #[test]
    fn launcher_execs_binary_with_run() {
        let s = launcher_script();
        assert!(s.starts_with("#!/bin/sh"));
        assert!(s.contains("exec \"$HOME/bin/macleaner\" run"));
        // The binary is exec'd from the boot drive, never from /Volumes.
        assert!(!s.contains("exec \"/Volumes"));
    }
}
